# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6a07ac0fd509fc3353d1d8de5d7b263b4e66ff57759d2fe5e22589813f10408b4351b2fcabebdffd956aefde09861a3ad1ead73ae666444ed2e71e928db3ac45

test:
  secret_key_base: 1d1df4dce363022379382e9943373947150c9c648c7fe06863c582546953c0debdd01cc47d15b5808f4bc7250de0e25650e80451ca31e07f7a6ca2346166354e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
