# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)
continents = Continent.create ([
  {name: "Europe"},
  {name: "Asia"},
  {name: "Australia"},
  {name: "North America"},
  {name: "South and Central America"},
  {name: "Africa"},
  {name: "Antarctica"}
  ])


countries = Country.create ([
  {alpha2code: "BD", name: "Bangladesh"},
  {alpha2code: "BE", name: "Belgium"},
  {alpha2code: "BF", name: "Burkina Faso"},
  {alpha2code: "BG", name: "Bulgaria"},
  {alpha2code: "BA", name: "Bosnia and Herzegovina"},
  {alpha2code: "BB", name: "Barbados"},
  {alpha2code: "WF", name: "Wallis and Futuna"},
  {alpha2code: "BL", name: "Saint Barthelemy"},
  {alpha2code: "BM", name: "Bermuda"},
  {alpha2code: "BN", name: "Brunei"},
  {alpha2code: "BO", name: "Bolivia"},
  {alpha2code: "BH", name: "Bahrain"},
  {alpha2code: "BI", name: "Burundi"},
  {alpha2code: "BJ", name: "Benin"},
  {alpha2code: "BT", name: "Bhutan"},
  {alpha2code: "JM", name: "Jamaica"},
  {alpha2code: "BV", name: "Bouvet Island"},
  {alpha2code: "BW", name: "Botswana"},
  {alpha2code: "WS", name: "Samoa"},
  {alpha2code: "BQ", name: "Bonaire, Saint Eustatius and Saba"},
  {alpha2code: "BR", name: "Brazil"},
  {alpha2code: "BS", name: "Bahamas"},
  {alpha2code: "JE", name: "Jersey"},
  {alpha2code: "BY", name: "Belarus"},
  {alpha2code: "BZ", name: "Belize"},
  {alpha2code: "RU", name: "Russia"},
  {alpha2code: "RW", name: "Rwanda"},
  {alpha2code: "RS", name: "Serbia"},
  {alpha2code: "TL", name: "East Timor"},
  {alpha2code: "RE", name: "Reunion"},
  {alpha2code: "TM", name: "Turkmenistan"},
  {alpha2code: "TJ", name: "Tajikistan"},
  {alpha2code: "RO", name: "Romania"},
  {alpha2code: "TK", name: "Tokelau"},
  {alpha2code: "GW", name: "Guinea-Bissau"},
  {alpha2code: "GU", name: "Guam"},
  {alpha2code: "GT", name: "Guatemala"},
  {alpha2code: "GS", name: "South Georgia and the South Sandwich Islands"},
  {alpha2code: "GR", name: "Greece"},
  {alpha2code: "GQ", name: "Equatorial Guinea"},
  {alpha2code: "GP", name: "Guadeloupe"},
  {alpha2code: "JP", name: "Japan"},
  {alpha2code: "GY", name: "Guyana"},
  {alpha2code: "GG", name: "Guernsey"},
  {alpha2code: "GF", name: "French Guiana"},
  {alpha2code: "GE", name: "Georgia"},
  {alpha2code: "GD", name: "Grenada"},
  {alpha2code: "GB", name: "United Kingdom"},
  {alpha2code: "GA", name: "Gabon"},
  {alpha2code: "SV", name: "El Salvador"},
  {alpha2code: "GN", name: "Guinea"},
  {alpha2code: "GM", name: "Gambia"},
  {alpha2code: "GL", name: "Greenland"},
  {alpha2code: "GI", name: "Gibraltar"},
  {alpha2code: "GH", name: "Ghana"},
  {alpha2code: "OM", name: "Oman"},
  {alpha2code: "TN", name: "Tunisia"},
  {alpha2code: "JO", name: "Jordan"},
  {alpha2code: "HR", name: "Croatia"},
  {alpha2code: "HT", name: "Haiti"},
  {alpha2code: "HU", name: "Hungary"},
  {alpha2code: "HK", name: "Hong Kong"},
  {alpha2code: "HN", name: "Honduras"},
  {alpha2code: "HM", name: "Heard Island and McDonald Islands"},
  {alpha2code: "VE", name: "Venezuela"},
  {alpha2code: "PR", name: "Puerto Rico"},
  {alpha2code: "PS", name: "Palestinian Territory"},
  # "PW": "Palau",
  # "PT": "Portugal",
  # "SJ": "Svalbard and Jan Mayen",
  # "PY": "Paraguay",
  # "IQ": "Iraq",
  # "PA": "Panama",
  # "PF": "French Polynesia",
  # "PG": "Papua New Guinea",
  # "PE": "Peru",
  # "PK": "Pakistan",
  # "PH": "Philippines",
  # "PN": "Pitcairn",
  # "PL": "Poland",
  # "PM": "Saint Pierre and Miquelon",
  # "ZM": "Zambia",
  # "EH": "Western Sahara",
  # "EE": "Estonia",
  # "EG": "Egypt"},
  # "ZA": "South Africa"},
  # "EC": "Ecuador"},
  # "IT": "Italy"},
  # "VN": "Vietnam"},
  # "SB": "Solomon Islands"},
  # "ET": "Ethiopia"},
  # "SO": "Somalia"},
  # "ZW": "Zimbabwe"},
  # "SA": "Saudi Arabia"},
  # "ES": "Spain"},
  # "ER": "Eritrea"},
  # "ME": "Montenegro"},
  # "MD": "Moldova"},
  # "MG": "Madagascar"},
  # "MF": "Saint Martin"},
  # "MA": "Morocco"},
  # "MC": "Monaco"},
  # "UZ": "Uzbekistan"},
  # "MM": "Myanmar"},
  # "ML": "Mali"},
  # "MO": "Macao"},
  # "MN": "Mongolia"},
  # "MH": "Marshall Islands"},
  # "MK": "Macedonia"},
  # "MU": "Mauritius"},
  # "MT": "Malta"},
  # "MW": "Malawi"},
  # "MV": "Maldives"},
  # "MQ": "Martinique"},
  # "MP": "Northern Mariana Islands"},
  # "MS": "Montserrat"},
  # "MR": "Mauritania"},
  # "IM": "Isle of Man"},
  # "UG": "Uganda"},
  # "TZ": "Tanzania"},
  # "MY": "Malaysia"},
  # "MX": "Mexico"},
  # "IL": "Israel"},
  # "FR": "France"},
  # "IO": "British Indian Ocean Territory"},
  # "SH": "Saint Helena"},
  # "FI": "Finland"},
  # "FJ": "Fiji"},
  # "FK": "Falkland Islands"},
  # "FM": "Micronesia"},
  # "FO": "Faroe Islands"},
  # "NI": "Nicaragua"},
  # "NL": "Netherlands"},
  # "NO": "Norway"},
  # "NA": "Namibia"},
  # "VU": "Vanuatu"},
  # "NC": "New Caledonia"},
  # "NE": "Niger"},
  # "NF": "Norfolk Island"},
  # "NG": "Nigeria"},
  # "NZ": "New Zealand"},
  # "NP": "Nepal"},
  # "NR": "Nauru"},
  # "NU": "Niue"},
  # "CK": "Cook Islands"},
  # "XK": "Kosovo"},
  # "CI": "Ivory Coast"},
  # "CH": "Switzerland"},
  # "CO": "Colombia"},
  # "CN": "China"},
  # "CM": "Cameroon"},
  # "CL": "Chile"},
  # "CC": "Cocos Islands"},
  # "CA": "Canada"},
  # "CG": "Republic of the Congo"},
  # "CF": "Central African Republic"},
  # "CD": "Democratic Republic of the Congo"},
  # "CZ": "Czech Republic"},
  # "CY": "Cyprus"},
  # "CX": "Christmas Island"},
  # "CR": "Costa Rica"},
  # "CW": "Curacao"},
  # "CV": "Cape Verde"},
  # "CU": "Cuba"},
  # "SZ": "Swaziland"},
  # "SY": "Syria"},
  # "SX": "Sint Maarten"},
  # "KG": "Kyrgyzstan"},
  # "KE": "Kenya"},
  # "SS": "South Sudan"},
  # "SR": "Suriname"},
  # "KI": "Kiribati"},
  # "KH": "Cambodia"},
  # "KN": "Saint Kitts and Nevis"},
  # "KM": "Comoros"},
  # "ST": "Sao Tome and Principe"},
  # "SK": "Slovakia"},
  # "KR": "South Korea"},
  # "SI": "Slovenia"},
  # "KP": "North Korea"},
  # "KW": "Kuwait"},
  # "SN": "Senegal"},
  # "SM": "San Marino"},
  # "SL": "Sierra Leone"},
  # "SC": "Seychelles"},
  # "KZ": "Kazakhstan"},
  # "KY": "Cayman Islands"},
  # "SG": "Singapore"},
  # "SE": "Sweden"},
  # "SD": "Sudan"},
  # "DO": "Dominican Republic"},
  # "DM": "Dominica"},
  # "DJ": "Djibouti"},
  # "DK": "Denmark"},
  # "VG": "British Virgin Islands"},
  # "DE": "Germany"},
  # "YE": "Yemen"},
  # "DZ": "Algeria"},
  # "US": "United States"},
  # "UY": "Uruguay"},
  # "YT": "Mayotte"},
  # "UM": "United States Minor Outlying Islands"},
  # "LB": "Lebanon"},
  # "LC": "Saint Lucia"},
  # "LA": "Laos"},
  # "TV": "Tuvalu"},
  # "TW": "Taiwan"},
  # "TT": "Trinidad and Tobago"},
  # "TR": "Turkey"},
  # "LK": "Sri Lanka"},
  # "LI": "Liechtenstein"},
  # "LV": "Latvia"},
  # "TO": "Tonga"},
  # "LT": "Lithuania"},
  # "LU": "Luxembourg"},
  # "LR": "Liberia"},
  # "LS": "Lesotho"},
  # "TH": "Thailand"},
  # "TF": "French Southern Territories"},
  # "TG": "Togo"},
  # "TD": "Chad"},
  # "TC": "Turks and Caicos Islands"},
  # "LY": "Libya"},
  # "VA": "Vatican"},
  # "VC": "Saint Vincent and the Grenadines"},
  # "AE": "United Arab Emirates"},
  # "AD": "Andorra"},
  # "AG": "Antigua and Barbuda"},
  # "AF": "Afghanistan"},
  # "AI": "Anguilla"},
  # "VI": "U.S. Virgin Islands"},
  # "IS": "Iceland"},
  # "IR": "Iran"},
  # "AM": "Armenia"},
  # "AL": "Albania"},
  # "AO": "Angola"},
  # "AQ": "Antarctica"},
  # "AS": "American Samoa"},
  # "AR": "Argentina"},
  # "AU": "Australia"},
  # "AT": "Austria"},
  # "AW": "Aruba"},
  # "IN": "India"},
  # "AX": "Aland Islands"},
  # "AZ": "Azerbaijan"},
  # "IE": "Ireland"},
  # "ID": "Indonesia"},
  # "UA": "Ukraine"},
  # "QA": "Qatar"},
  {alpha2code: "MZ", name: "Mozambique"}
  ])
